name: grocery
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.0.3+1
  bloc: ^8.1.2
  provider: ^6.0.5
  url_launcher: ^6.1.10
  http: ^0.13.5
  randomstring_dart: ^0.0.4
  webview_flutter: ^4.0.7
  webview_flutter_wkwebview: ^3.1.1
  shimmer: ^3.0.0
  connectivity_plus: ^2.3.9
  abushakir: ^1.0.0
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_inappwebview: ^5.8.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/splash.png
    - assets/images/signin.png
    - assets/images/banana.png
    - assets/images/ice-cream.png
    - assets/images/milk.png
    
    - assets/images/banana2.png
    - assets/images/broccoli.png
    - assets/images/cabbage.png
    - assets/images/garlic.png
    - assets/images/ice-cream.png
    - assets/images/onion.png
    - assets/images/oranage.png
    - assets/images/potato.png
    - assets/images/tomato.png

    - assets/images/bread.png
    - assets/images/dairy.png
    - assets/images/eggs.png
    - assets/images/fruits.png
    - assets/images/mushroom.png
    - assets/images/oats.png
    - assets/images/rice.png
    - assets/images/vegetables.png

    - assets/images/lady.png

    - assets/images/banana_detail.png
    - assets/images/bronci_detail.png
    - assets/images/mushroom_details.png

    - assets/images/thank_you.png

    - assets/images/splash_logo.png

    - assets/images/electrinics.jpg
    - assets/images/jewelery.jpg
    - assets/images/mens_cloth.jpg
    - assets/images/womens_cloth.jpg

    - assets/images/ic_launcher.jpg



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
